version: '3.8'

services:
  lmsystem.api:
    container_name: lmsystem-api
    build:
      context: .
      dockerfile: LMSystem.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      
      # Database
      CONNECTION_STRING: ${CONNECTION_STRING}

      # JWT
      SECRET_KEY: ${SECRET_KEY}

      # Mail
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      # Paypal
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}

      # PayOS
      PAYOS_CLIENT_ID: ${PAYOS_CLIENT_ID}
      PAYOS_API_KEY: ${PAYOS_API_KEY}
      PAYOS_CHECKSUM: ${PAYOS_CHECKSUM}
      
      FIREBASE_CONFIG_BASE64: ${FIREBASE_CONFIG_BASE64}